POST http://localhost:7070/callback-logger/api/callback
Content-Type: application/json

{
  "clientId": "wallet_test",
  "requestId": "VCpcFPowVwzX",
  "timestamp": "2023-04-14T09:18:22.132Z",
  "callbackArgs": null,
  "transactions": [
    {
      "transactionId": "m2zMkIcqHXki",
      "transactionType": "pay",
      "statusCode": 100,
      "statusDescription": "The gateway has received the transaction.",
      "statusType": "pending",
      "finished": false
    }
  ],
  "finished": false
}

###

PUT http://localhost:7070/callback-logger/api/callback
Content-Type: application/xml

<CATALOG>
    <PLANT>
        <COMMON>Bloodroot</COMMON>
        <BOTANICAL>Sanguinaria canadensis</BOTANICAL>
        <ZONE>4</ZONE>
        <LIGHT>Mostly Shady</LIGHT>
        <PRICE>$2.44</PRICE>
        <AVAILABILITY>031599</AVAILABILITY>
    </PLANT>
    <PLANT>
        <COMMON>Columbine</COMMON>
        <BOTANICAL>Aquilegia canadensis</BOTANICAL>
        <ZONE>3</ZONE>
        <LIGHT>Mostly Shady</LIGHT>
        <PRICE>$9.37</PRICE>
        <AVAILABILITY>030699</AVAILABILITY>
    </PLANT>
    <PLANT>
        <COMMON>Marsh Marigold</COMMON>
        <BOTANICAL>Caltha palustris</BOTANICAL>
        <ZONE>4</ZONE>
        <LIGHT>Mostly Sunny</LIGHT>
        <PRICE>$6.81</PRICE>
        <AVAILABILITY>051799</AVAILABILITY>
    </PLANT>
</CATALOG>

###
